name: storyblok_client
description: Client for accessing the Storyblok Headless CMS API through Dart.
version: 1.0.1+1
homepage: https://github.com/essarn/storyblok_client
repository: https://github.com/essarn/storyblok_client
issue_tracker: https://github.com/essarn/storyblok_client/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.1
  enum_to_string: ^2.0.1
  meta: ^1.3.0
  intl: ^0.17.0
  recase: ^3.0.1

dev_dependencies:
  effective_dart: ^1.3.1
