name: storyblok_client
description: Client for accessing the Storyblok Headless CMS API through Dart.
version: 1.0.1+1
homepage: https://github.com/essarn/storyblok_client
repository: https://github.com/essarn/storyblok_client
issue_tracker: https://github.com/essarn/storyblok_client/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  enum_to_string: ^1.0.9
  meta: ^1.1.8
  intl: ^0.16.1
  recase: ^3.0.0

dev_dependencies:
  effective_dart: ^1.2.1
