name: storyblok_client
description: Client for accessing the Storyblok Headless CMS API through Dart.
version: 1.0.0
homepage: https://github.com/essarn/storyblok_client
repository: https://github.com/essarn/storyblok_client
issue_tracker: https://github.com/essarn/storyblok_client/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  enum_to_string: ^1.0.9
